version: "3"

services:
  chatgpt-discord-bot:
    build: .
    image: auragpt:latest
    container_name: auragpt
    env_file:
      - stack.env
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/portainer/portainer_data/compose/auragpt
        target: /DiscordBot
 
volumes:
  chatgpt-discord-bot:
